Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jBloger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Created { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jBloger.Models;
using System.Data.Entity;

namespace jBloger.Controllers
{
    public class BlogController : Controller
    {
        JonyModelConSet _db = new JonyModelConSet();
        // GET: Blog
        public ActionResult Indexx()
        {
            var posts = _db.Posts.ToList();
            
            return View(posts);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                
                post.Created = DateTime.Now.ToString();
                _db.Posts.Add(post);
                _db.SaveChanges();
                return RedirectToAction("Indexx");
            }
            return View(post);
        }

        public ActionResult Post(long? id) 
        {
            var post = _db.Posts.Find(id);
            return View(post);
        }
        [HttpPost]
        public ActionResult Post(long? id,Comment newComment)
        {
            if (ModelState.IsValid && id != null) 
            {
               newComment.Id == _db.Comments.Max(c => c.Id+1)
                    newComment.Post = (int)id;
                    newComment.Created = DateTime.Now.ToString();
                    _db.Comments.Add(newComment);
                    _db.SaveChanges();
                    return RedirectToAction("Post", new { Id = id });
                
            }
            return Post(id);
        }
        public ActionResult Edit(long? id)
        {
             return View(_db.Posts.Find(id));
        }
        [HttpPost]
        public ActionResult Edit(long? id, jBloger.Models.Post post)
        {
            if (ModelState.IsValid)
            {
                post.Created = DateTime.Now.ToString();
                _db.Entry(post).State = EntityState.Modified;
                 
                _db.SaveChanges();
                return RedirectToAction("Indexx");
            }
            return View(post);
        }

        public ActionResult Delete(long? id)
        {

            return View(_db.Posts.Find(id));

        }
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long? id, Post post)
        {

            Post posts = _db.Posts.Find(id);
            
            _db.Posts.Remove(posts);
            
            _db.SaveChanges();
            return RedirectToAction("Indexx");
        }
        
        public ActionResult DeleteComments(long? id)
        {

            return View(_db.Comments.Find(id));

        }
        [HttpPost, ActionName("DeleteComments")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteComments(long? id, Comment comment)
        {

            Comment comments = _db.Comments.Find(id);
            _db.Comments.Remove(comments);
            
            _db.SaveChanges();
            return RedirectToAction("Post");
        }
        public ActionResult EditComments(long? id)
        {
            return View(_db.Comments.Find(id));
        }
        [HttpPost]
        public ActionResult EditComments(long? id, jBloger.Models.Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Created = DateTime.Now.ToString();
                _db.Entry(comment).State = EntityState.Modified;
              // comment.Id = _db.Comments.Max(c => c.Id) + 1;
             // comment.Post = (int)id;
                
                _db.SaveChanges();
                return RedirectToAction("Post");
            }
            return View(comment);
        }
        public PartialViewResult AjaxSearch(string q)
        {
            var albums = _db.Posts.Where(a => a.Title.Contains(q)).Take(10);
            return this.PartialView(albums);
        }
            

    }
}

Views/Blog/AjaxSearch.cshtml
@model IEnumerable<jBloger.Models.Post>

@{
    ViewBag.Title = "AjaxSearch";
}

 <div>
    @foreach (var item in Model)
    {  <tr>

        <h2><a href="@Url.Action("Post", new {Id= item.Id})">@item.Title</a></h2>
        <small>@item.Created</small>
        <p>@item.Summary</p>
        
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) 
            @Html.ActionLink("Delete", "Delete", new { id = item.Id});
     </tr>     
    
    }
     

    </div>  
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Blog/Create.cshtml
@model jBloger.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         
        @Html.LabelFor(m => m.Title)
        @Html.EditorFor(m => m.Title)
        <hr />
        @Html.LabelFor(m => m.Summary)
        @Html.EditorFor(m => m.Summary)
        <hr />
        @Html.LabelFor(m => m.Content)
        @Html.EditorFor(m => m.Content)
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Indexx")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Blog/Delete.cshtml
@model jBloger.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">

            <input type="submit" value="Yes" class="btn btn-default" />  
          
            <hr />

            @Html.ActionLink("Back to List", "Indexx")
         
           
        </div>
    }
</div>

Views/Blog/DeleteComments.cshtml
@model jBloger.Models.Comment

@{
    ViewBag.Title = "DeleteComments";
}

<h2>DeleteComments</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Post")
        </div>
    }
</div>

Views/Blog/Edit.cshtml
@model jBloger.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Indexx")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Blog/EditComments.cshtml
@model jBloger.Models.Comment

@{
    ViewBag.Title = "EditComments";
}

<h2>Edit Comments</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Post, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Post, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Post, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Post")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Blog/Indexx.cshtml
@model IEnumerable<jBloger.Models.Post>

@{
    ViewBag.Title = "Indexx";
}

@using (Ajax.BeginForm("AjaxSearch", "Blog",
    new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "search" }))
{
    
    <input type="text" name="q" />
    
}

<table id="searchResults"></table>

<input type="submit" value="Ajax Search" class="btn btn-default" style="float: right; margin-left:10px;  " />
<input type="search" class="form-control" name="q" style="float: right" />

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th></th>
    </tr>*@
<div id="search">
@foreach (var item in Model) {
    @*<tr>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Summary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>*@
    
    <h2><a href="@Url.Action("Post", new {Id= item.Id})">@item.Title</a></h2>
    <small>@item.Created</small>
    <p>@item.Summary</p>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
}

@*</table>*@

</div>

Views/Blog/Post.cshtml
@model jBloger.Models.Post

@{
    ViewBag.Title = "Post";
}

<h1>@Model.Title</h1>
<blockquote style="word-wrap: break-word; margin-top: 2%"><i>@Model.Summary</i></blockquote>
<p style="text-indent: 20px"><span style="word-wrap: break-word">@Model.Content</span></p>

  <hr />
     <i style="float: left; margin-left: 1%; margin-bottom: 2%">@Model.Created</i>
      <i style="float:right; margin-right: 1%; margin-bottom: 2%">Author</i>
  <hr style="margin-top: 3%; clear:both" />
    <h3>Comments</h3>

    @foreach (var comment in Model.Comments)
    {
        <div class="comment" style="word-wrap: break-word">
            <small>@comment.Created | @comment.Author</small>
            <p>@comment.Content</p>

            @Html.ActionLink("Edit", "EditComments", new { id = comment.Id }) |
            @Html.ActionLink("Delete", "DeleteComments", new { id = comment.Id })
            <hr />
        </div>
    }

    @using (Html.BeginForm())
    {
        <p>Autor: @Html.TextBox("NewComment.Author")</p>
        <p>Text:  @Html.TextArea("NewComment.Content")</p>
        <p><input type="submit" value="Send" /></p>
    }

    @Html.ActionLink("Back", "Indexx")